### ISSUE TITLE
proposal & discussion, add a GitHub Action

### ISSUE THREAD

**Issue by jackalcooper** [makslevental/mlir-wheels#25]
- to install latest wheels with a cron workflow
- or to specify a version
- example
```yml
- name: Install MLIR
  uses: makslevental/mlir-wheels@v1
  with:
    version: "latest"
```
- reference: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
